title: Cyber Portfolio
description: Portfolio description
theme: just-the-docs

url: https://glemieux019.github.io

aux_links:
  Template Repository: https://github.com/glemieux019/Cyber-Portfolio

logo: "/assets/images/bibi.jpg"